# Containers user storage configuration file

[storage]
driver = "overlay"
rootless_storage_path="$HOME/goinfre/containers/storage"
runroot="$HOME/.local/share/containers/storage"

[storage.options]
additionalimagestores = ["/goinfre/containers/storage"]
