#!/bin/bash

function print_help() {
	echo 1>&2 \
		"A towel is just about the most massively useful thing an interstellar hitchhiker can carry.

Usage:
  towel [options] [command]
  'enter' is default if no command is given

Available Commands:
  create   Create towel container
  enter    Enter towel container
  export   Export installed package apps/binaries to host wrappers
  install  Install package inside the towel container (prompts for host export)
  remove   Remove towel container, cannot be undone

Install Options:
  -y, --yes  Assume yes to export prompt during install

Options:
  -h       Print this help text"
	exit 0
}

function unknown_command() {
	echo 1>&2 "Unknown command \`towel $1'"
	echo 1>&2 "Try \`towel -h'"
	exit 1
}

function unknown_option() {
	echo 1>&2 "Unknown option \`towel $1'"
	echo 1>&2 "Try \`towel -h'"
	exit 1
}
