#!/bin/bash

source "$TOWEL_LIB/help"

declare -A arg_handlers=([create]="towel_create" [exec]="towel_exec" [enter]="towel_enter" [export]="towel_export" [install]="towel_install" [remove]="towel_remove")
declare -A opt_handlers=([-h]="print_help")

function towel_parse_args () {
	shopt -s extglob
	while [[ $# -gt 0 ]]; do
		arg="$1"
		if [[ " ${!opt_handlers[*]} " == *" $arg "* ]]; then
			handler="${opt_handlers[$arg]}"
			shift
			"$handler" "$@"
		elif [[ " ${!arg_handlers[*]} " == *" $arg "* ]]; then
			shift
			declare -ga towel_command=("${arg_handlers[$arg]}" "$@")
			return # Command found, return to main loop to execute it
		else
			[[ "$arg" == -* ]] && unknown_option "$arg" 
			unknown_command "$arg"
			exit 1
		fi
		declare -ga towel_command=("${arg_handlers[enter]}" "$@")
	done
}
