#!/bin/bash

TOWEL_INI="/etc/distrobox/distrobox.ini"

function inside_towel() {
	[ -n "$CONTAINER_ID" ] && [ "$CONTAINER_ID" = "towel" ] >/dev/null 2>&1
}

function towel_sanity_check() {
	if [ -n "$CONTAINER_ID" ]; then
		builtin echo "Command shouldn't be run inside a container, rerun command on the host system." 1>&2
		exit 1
	fi
}

function towel_exists() {
	podman container exists towel >/dev/null 2>&1
}

function towel_create() {
	towel_sanity_check
	distrobox assemble create --file "$TOWEL_INI"
}

function towel_enter() {
	towel_sanity_check
	if ! towel_exists; then
		builtin echo "No such container towel"
		while builtin read -rp "Create it now? yes|No:"; do
			case "$REPLY" in
			y | yes | Y | Yes | YES)
				towel_create
				break
				;;
			n | no | N | No | NO)
				:
				;;
			*)
				echo "Invalid input." 1>&2
				;;
			esac
			exit 1
		done
	fi
	distrobox enter towel
}

function towel_exec() {
	local ret=0
	if [ -z "${CONTAINER_ID}" ]; then
		distrobox-enter -n towel -- "$HOME/.local/bin/towel" exec "$@"
		ret=$?
		if [ $ret -ne 0 ]; then
			local should_prompt=false
			if ! towel_exists; then
				should_prompt=true
				local msg="Container 'towel' does not exist."
			elif ! distrobox-enter -n towel -- command -v "$1" >/dev/null 2>&1; then
				should_prompt=true
				local msg="Command '$1' not found in towel."
			fi

			if [[ "$should_prompt" == true ]]; then
				local ans="n"
				if [ -t 0 ]; then
					read -rp "towel: $msg Remove exported app? [y/N] " ans </dev/tty || true
				else
					if command -v zenity >/dev/null 2>&1; then
						zenity --question --title="$1 on towel" --text="${msg:-"Command failed."} Remove exported app?" 2>/dev/null && ans="y" || ans="n"
					fi
				fi
				case "$ans" in
				[Yy]*)
					towel_remove_exported_apps "$1"
					;;
				esac
			fi
		fi
	elif ! inside_towel; then
		/usr/bin/distrobox-host-exec "$HOME/.local/bin/towel" exec "$@"
		ret=$?
	else
		"$@"
		ret=$?
	fi
	exit $ret
}

function towel_remove() {
	towel_sanity_check

	towel_remove_exported_apps

	distrobox assemble rm --file "$TOWEL_INI"
}
