unqualified-search-registries=["https://nexus.codam.nl:5004"]

[[registries]]
prefix = "docker.io"
location = "nexus.codam.nl:5004"

[[registries]]
prefix = "quay.io"
location = "nexus.codam.nl:5004"

