unqualified-search-registries = ["docker.io"]

[[registry]]
prefix = "quay.io"
location = "quay.io"
[[registry.mirror]]
location = "nexus.codam.nl:5004"

[[registry]]
prefix = "ghcr.io"
location = "ghcr.io"
[[registry.mirror]]
location = "nexus.codam.nl:5004"

[[registry]]
prefix = "docker.io"
location = "docker.io"
[[registry.mirror]]
location = "nexus.codam.nl:5004"
