# Containers system storage configuration file

[storage]
driver="overlay"
graphroot="/goinfre/containers/storage"
runroot="/goinfre/containers/storage"

[storage.options]
additionalimagestores=["/sgoinfre/containers/storage", "/goinfre/containers/storage"]

